# Generated by Django 3.1.7 on 2021-05-27 22:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0002_archivo_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportes',
            name='usuario',
        ),
        migrations.AddField(
            model_name='reportes',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='nombre',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='archivo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='principal.archivo'),
        ),
        migrations.AlterOrderWithRespectTo(
            name='archivo',
            order_with_respect_to=None,
        ),
    ]
