# Generated by Django 3.1.7 on 2021-05-27 23:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0005_archivo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='nombre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='tipo',
            field=models.CharField(choices=[('Declaracion', 'Declaracion'), ('Reporte mensual', 'Reporte mensual')], max_length=100, null=True),
        ),
    ]
