# Generated by Django 3.1.7 on 2021-05-29 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20210527_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(null=True, upload_to='static/archivos'),
        ),
    ]
