# Generated by Django 3.1.7 on 2021-05-29 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0007_auto_20210529_0747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportes',
            old_name='user',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='reportes',
            name='date_created',
        ),
        migrations.AddField(
            model_name='reportes',
            name='año',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='reportes',
            name='mes',
            field=models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos'),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos'),
        ),
        migrations.CreateModel(
            name='Declaraciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo')], max_length=100, null=True)),
                ('año', models.CharField(choices=[('Enero', 'Enero'), ('Febrero', 'Febrero'), ('Marzo', 'Marzo')], max_length=100, null=True)),
                ('archivo', models.FileField(null=True, upload_to='archivos')),
                ('nombre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Declaraciones',
            },
        ),
    ]
