# Generated by Django 3.1.7 on 2021-05-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0008_auto_20210529_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaraciones',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos/declaraciones'),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='archivo',
            field=models.FileField(null=True, upload_to='archivos/reportes'),
        ),
    ]
