# Generated by Django 3.1.7 on 2021-05-29 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0009_auto_20210529_0807'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reportes',
            options={'verbose_name_plural': 'Reportes'},
        ),
        migrations.AlterField(
            model_name='declaraciones',
            name='año',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='reportes',
            name='año',
            field=models.CharField(choices=[('2020', '2020'), ('2021', '2021'), ('2022', '2022')], max_length=100, null=True),
        ),
    ]
