# Generated by Django 3.1.7 on 2021-05-29 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0010_auto_20210529_0828'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Archivo',
        ),
    ]
